// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL4_cJD3vYIh29RmvhMVR_cdxIRgCYq18',
    appId: '1:52362093003:web:3cd44d990cfcf20e48564e',
    messagingSenderId: '52362093003',
    projectId: 'quoteapp-4ccab',
    authDomain: 'quoteapp-4ccab.firebaseapp.com',
    storageBucket: 'quoteapp-4ccab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQMcBCyS2ks9bVVDriX4ecKphS0KOyVKo',
    appId: '1:52362093003:android:fbf25fdd21e4009548564e',
    messagingSenderId: '52362093003',
    projectId: 'quoteapp-4ccab',
    storageBucket: 'quoteapp-4ccab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt4z8kopvdQCsIv_DDqQj3RXna5C0v4IQ',
    appId: '1:52362093003:ios:6e3479b75dd2d40448564e',
    messagingSenderId: '52362093003',
    projectId: 'quoteapp-4ccab',
    storageBucket: 'quoteapp-4ccab.firebasestorage.app',
    iosBundleId: 'com.example.quotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt4z8kopvdQCsIv_DDqQj3RXna5C0v4IQ',
    appId: '1:52362093003:ios:6e3479b75dd2d40448564e',
    messagingSenderId: '52362093003',
    projectId: 'quoteapp-4ccab',
    storageBucket: 'quoteapp-4ccab.firebasestorage.app',
    iosBundleId: 'com.example.quotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL4_cJD3vYIh29RmvhMVR_cdxIRgCYq18',
    appId: '1:52362093003:web:27b83ad88500c50448564e',
    messagingSenderId: '52362093003',
    projectId: 'quoteapp-4ccab',
    authDomain: 'quoteapp-4ccab.firebaseapp.com',
    storageBucket: 'quoteapp-4ccab.firebasestorage.app',
  );
}
