// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnD_ufFUlk2AUogh9v_0F1nLlDm6WftZE',
    appId: '1:128077883868:web:65bb496d58617adac00719',
    messagingSenderId: '128077883868',
    projectId: 'flutterdemo-e4925',
    authDomain: 'flutterdemo-e4925.firebaseapp.com',
    storageBucket: 'flutterdemo-e4925.firebasestorage.app',
    measurementId: 'G-T79M3MWFK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGS_PpBKnyFrzlqOspASrT-f9yL01NZuw',
    appId: '1:128077883868:android:496218bfe26ab74fc00719',
    messagingSenderId: '128077883868',
    projectId: 'flutterdemo-e4925',
    storageBucket: 'flutterdemo-e4925.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqpn1JwJI6qGBlR0CqQfbhVJZmUYXel-Q',
    appId: '1:128077883868:ios:cd073c6805deb72fc00719',
    messagingSenderId: '128077883868',
    projectId: 'flutterdemo-e4925',
    storageBucket: 'flutterdemo-e4925.firebasestorage.app',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqpn1JwJI6qGBlR0CqQfbhVJZmUYXel-Q',
    appId: '1:128077883868:ios:cd073c6805deb72fc00719',
    messagingSenderId: '128077883868',
    projectId: 'flutterdemo-e4925',
    storageBucket: 'flutterdemo-e4925.firebasestorage.app',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnD_ufFUlk2AUogh9v_0F1nLlDm6WftZE',
    appId: '1:128077883868:web:f4ad30b347d6e95cc00719',
    messagingSenderId: '128077883868',
    projectId: 'flutterdemo-e4925',
    authDomain: 'flutterdemo-e4925.firebaseapp.com',
    storageBucket: 'flutterdemo-e4925.firebasestorage.app',
    measurementId: 'G-V241BWEZNY',
  );
}
